#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.1.0.build{build}

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      ARCH: "32"
      CONDARC: .condarc-32
    
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      ARCH: "64"
      CONDARC: .condarc

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda info --all
  - conda create -n _dtocean_app python=%PYTHON_VERSION% pip pyyaml
  - activate _dtocean_app
  - copy %CONDARC% %CONDA_PREFIX%\\.condarc
  - conda install polite==0.10.1 aneris==0.11.1 dtocean-core==3.0.0 dtocean-qt==0.10.1
  - conda install --file requirements-conda-dev.txt
  - python setup.py bootstrap
  - pip install -e .
  - conda install mock "pytest>=3.6,<4" pytest-cov pytest-mock pytest-qt

build: off

test_script:
  - py.test --cov dtocean_app tests

after_test:
 - pip install codecov
 - codecov
 
# on_finish:
 # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
