---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
handlers:
  null:
    class: logging.NullHandler
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class : logging.handlers.TimedRotatingFileHandler
    formatter: simple
    level: DEBUG
    filename: dtocean-app.log
    when: D
  widget:
    class: dtocean_app.utils.qtlog.QtHandler
    level: INFO
    formatter: simple
loggers:
  'dtocean_app':
    level: DEBUG
    handlers: [widget, file]
    propagate: no
root:
  level: DEBUG
  handlers: [widget, file]

